Loading LIBD SLURM module for ldsc/1.0.1
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 2] No such file or directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/sLDSC_coefficients/snRNA-seq_aggregated_cpm.tsv/adhd.out.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 2] No such file or directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/sLDSC_coefficients/snRNA-seq_aggregated_cpm.tsv/alcohol_ldscore.out.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 2] No such file or directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/sLDSC_coefficients/snRNA-seq_aggregated_cpm.tsv/Alzheimer_ldscore.out.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 2] No such file or directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/sLDSC_coefficients/snRNA-seq_aggregated_cpm.tsv/Alzheimer_ldscore2.out.log'
