Loading LIBD SLURM module for ldsc/1.0.1
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.7.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.8.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.9.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.10.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.11.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.12.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.13.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.14.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.15.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.16.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.17.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.18.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.19.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.20.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.21.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/snRNA_seq/input_files/snRNA-seq_aggregated_cpm.tsv/chr.22.log'
