Loading LIBD SLURM module for ldsc/1.0.1
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/10x_visium/input_files/10x_visium_aggregated_cpm.tsv/chr.17.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/10x_visium/input_files/10x_visium_aggregated_cpm.tsv/chr.18.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/10x_visium/input_files/10x_visium_aggregated_cpm.tsv/chr.19.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/10x_visium/input_files/10x_visium_aggregated_cpm.tsv/chr.20.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/10x_visium/input_files/10x_visium_aggregated_cpm.tsv/chr.21.log'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 587, in <module>
    log = Logger(args.out+'.log')
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/ldsc.py", line 76, in __init__
    self.log_fh = open(fh, 'wb')
IOError: [Errno 20] Not a directory: '/dcs04/lieber/marmaypag/spatialNac_LIBD4125/spatial_NAc/processed-data/19_sLDSC/10x_visium/input_files/10x_visium_aggregated_cpm.tsv/chr.22.log'
