
EnvironmentNameNotFound: Could not find conda environment: ldsc
You can list all discoverable environments with `conda info --envs`.


Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Traceback (most recent call last):
  File "/dcs04/lieber/shared/statsgen/LDSC/base/scripts/make_annot.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
